### PR TITLE
fix warning 'FixedBy' when I scanning a image

### PR DESCRIPTION
**Pull request by botranvan**
When i scanning image. I see a vul haven't attribute FixedBy and so on..
I decided fix it

### CODE REVIEW

**Comment by joelee2012** [comment]
one check is failed, can you make it successful ?

**Comment by BoTranVan** [comment]
Yes, i can and now, i still using my code.

**Comment by botranvan** [comment]
Now, i still using my code but i don't know anything about travis.
I see on log with error:
```
0.65s$ git clone --depth=50 https://github.com/joelee2012/claircli.git joelee2012/claircli
Cloning into 'joelee2012/claircli'...
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 49 (delta 11), reused 49 (delta 11), pack-reused 0
Receiving objects: 100% (49/49), 28.95 KiB | 4.82 MiB/s, done.
Resolving deltas: 100% (11/11), done.
$ cd joelee2012/claircli
4.30s$ git fetch origin +refs/pull/6/merge:
fatal: couldn't find remote ref refs/pull/6/merge
The command "eval git fetch origin +refs/pull/6/merge: " failed. Retrying, 2 of 3.
fatal: couldn't find remote ref refs/pull/6/merge
The command "eval git fetch origin +refs/pull/6/merge: " failed. Retrying, 3 of 3.
fatal: couldn't find remote ref refs/pull/6/merge
The command "eval git fetch origin +refs/pull/6/merge: " failed 3 times.
The command "git fetch origin +refs/pull/6/merge:" failed and exited with 128 during .
Your build has been stopped.
```
Could you tell me why have this errors?

**Comment by joelee2012** [comment]
it seems you abort commit #6

**Comment by botranvan** [comment]
Ok, i had done.
Thank you very much for help me!

**Pull request merged**
